global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: "prometheus" 
    static_configs:
      - targets: ["localhost:9090"] 

  - job_name: "mysqld_exporter"
    static_configs:
      - targets: ["mysqld_exporter:9104"]

   - job_name: 'flask_app'
     static_configs:
      - targets: ['flask:5000']
